export const initialLeadsData = [
  {
    id: 15,
    createdAt: '2026-06-15T09:00:00Z',
    company: 'Horizon Retail',
    projectName: 'Horizon Retail Omnichannel Commerce Transformation',
    contact: 'David Smith',
    stage: 'Proposal',
    status: 'Proposal Sent',
    value: '$45,000',
    industry: 'Retail',
    size: '100-500',
    region: 'North America',
    priority: 'Normal',
    owner: 'D. Ghosh',
    source: 'Website',
    score: 65,
    prob: 40,
    sentiment: 'Positive',
    criteria: { bestTime: 'Afternoons (2 PM - 4 PM)', requirements: 'Retail management system implementation' },
    altContact: { name: 'Sarah Chen', phone: '9876543210', email: 'sarah.chen@gmail.com' },
    productService: { products: ['Enterprise Retail Suite'], services: ['Customization Consulting'] },
    requestType: { category: 'Product Request', type: 'Enterprise Software' },
    estDate: '2026-08-15',
    linkedin: { profile: 'linkedin.com/in/davidsmith', company: 'linkedin.com/company/horizon-retail' },
    commercial: { opportunities: 1, closingValue: '$45,000', estDealValue: '$18,000', valWithTax: '$53,100', valWithoutTax: '$45,000', commPercent: '10%', commAmount: '$4,500' },
    partners: [],
    history: [
      { date: '2026-06-15', action: 'Lead Created', user: 'System', time: '09:00 AM', type: 'system', description: 'Lead ingested from website signup form' },
      { date: '2026-06-15', action: 'Lead Assigned', user: 'System', time: '09:05 AM', type: 'system', description: 'Assigned to D. Ghosh based on round-robin routing' },
      { date: '2026-06-16', action: 'Initial Contact', user: 'D. Ghosh', time: '11:30 AM', type: 'call', description: 'Discovery call completed. Client is looking for multi-store POS sync.' },
      { date: '2026-06-20', action: 'Proposal Shared', user: 'D. Ghosh', time: '03:15 PM', type: 'email', description: 'Sent initial pricing proposal and product brochure' }
    ],
    isOverdue: false
  },
  {
    id: 16,
    createdAt: '2026-06-16T10:00:00Z',
    company: 'Zenith Financial',
    projectName: 'Zenith Financial Risk & Compliance Modernization',
    contact: 'Alice Cooper',
    stage: 'Negotiation',
    status: 'Negotiation',
    value: '$120,000',
    industry: 'Finance',
    size: '500+',
    region: 'Europe',
    priority: 'High',
    owner: 'S. Mishra',
    source: 'LinkedIn',
    score: 85,
    prob: 75,
    sentiment: 'Positive',
    criteria: { bestTime: 'Morning (9 AM - 11 AM)', requirements: 'Risk assessment engine compliance upgrade' },
    altContact: { name: 'Bob Dylan', phone: '9887766554', email: 'bob.dylan@gmail.com' },
    productService: { products: ['Financial Analytics API'], services: ['Integration Support'] },
    requestType: { category: 'Service Request', type: 'SLA Support Integration' },
    estDate: '2026-07-06', // Overdue by 1 day as local date is July 7
    linkedin: { profile: 'linkedin.com/in/alicecooper', company: 'linkedin.com/company/zenith-financial' },
    commercial: { opportunities: 2, closingValue: '$120,000', estDealValue: '$90,000', valWithTax: '$141,600', valWithoutTax: '$120,000', commPercent: '10%', commAmount: '$12,000' },
    partners: [],
    history: [
      { date: '2026-06-16', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Lead imported from LinkedIn Campaign' },
      { date: '2026-06-17', action: 'Phone Call', user: 'S. Mishra', time: '02:00 PM', type: 'call', description: 'Discussed architectural requirements and SLA levels' },
      { date: '2026-06-25', action: 'Demo Conducted', user: 'S. Mishra', time: '11:00 AM', type: 'meeting', description: 'Conducted technical demo with IT steering committee' },
      { date: '2026-06-30', action: 'Negotiation Started', user: 'S. Mishra', time: '04:30 PM', type: 'meeting', description: 'Reviewing pricing schedules and payment terms' }
    ],
    isOverdue: true
  },
  {
    id: 22,
    createdAt: '2026-06-17T11:00:00Z',
    company: 'NovaMed Healthcare',
    projectName: 'NovaMed Healthcare Patient Data Modernization',
    contact: 'Jennifer Wu',
    stage: 'Needs Analysis',
    status: 'Contacted',
    value: '$85,000',
    industry: 'Healthcare',
    size: '100-500',
    region: 'North America',
    priority: 'High',
    owner: 'H. Kumar',
    source: 'LinkedIn',
    score: 78,
    prob: 30,
    sentiment: 'Positive',
    criteria: { bestTime: 'Afternoons (2 PM - 4 PM)', requirements: 'Patient data migration and cloud database setup' },
    altContact: { name: 'Dr. John Watson', phone: '9776655443', email: 'watson.med@gmail.com' },
    productService: { products: ['Healthcare Cloud Platform'], services: ['Data Migration Support'] },
    requestType: { category: 'Product Request', type: 'Cloud Data Setup' },
    estDate: '2026-07-02', // Overdue by 5 days
    linkedin: { profile: 'linkedin.com/in/jenniferwu', company: 'linkedin.com/company/novamed-healthcare' },
    commercial: { opportunities: 1, closingValue: '$85,000', estDealValue: '$25,500', valWithTax: '$100,300', valWithoutTax: '$85,000', commPercent: '10%', commAmount: '$8,500' },
    partners: [],
    history: [
      { date: '2026-06-17', action: 'Lead Created', user: 'System', time: '11:00 AM', type: 'system', description: 'Lead generated via partner database upload' },
      { date: '2026-06-18', action: 'Email Sent', user: 'H. Kumar', time: '10:00 AM', type: 'email', description: 'Sent introduction package and requested discovery call availability' },
      { date: '2026-06-22', action: 'Initial Contact', user: 'H. Kumar', time: '03:00 PM', type: 'call', description: 'Discovery call completed. Client requested custom security checklist.' }
    ],
    isOverdue: true
  },
  {
    id: 28,
    createdAt: '2026-06-14T14:30:00Z',
    company: 'Quantum Tech',
    projectName: 'Quantum Tech Cloud ERP Enablement',
    contact: 'Alex Rodriguez',
    stage: 'Negotiation',
    status: 'Negotiation',
    value: '$210,000',
    industry: 'Technology',
    size: '50-200',
    region: 'North America',
    priority: 'Urgent',
    owner: 'P. Sharma',
    source: 'Cold Call',
    score: 95,
    prob: 90,
    sentiment: 'Interested',
    criteria: { bestTime: 'Anytime', requirements: 'Full suite CRM replacement before Q4' },
    altContact: { name: 'Sarah Connor', phone: '9665544332', email: 'sconnor.t@gmail.com' },
    productService: { products: ['SalesTracker Enterprise Plus'], services: ['Premium Support', 'Data Migration'] },
    requestType: { category: 'Product Request', type: 'Enterprise Software' },
    estDate: '2026-07-08', // Due Tomorrow
    linkedin: { profile: 'linkedin.com/in/alexrod', company: 'linkedin.com/company/quantumtech' },
    commercial: { opportunities: 3, closingValue: '$210,000', estDealValue: '$189,000', valWithTax: '$247,800', valWithoutTax: '$210,000', commPercent: '12%', commAmount: '$25,200' },
    partners: ['TechIntegrators Inc'],
    history: [
      { date: '2026-06-14', action: 'Lead Created', user: 'System', time: '02:30 PM', type: 'system', description: 'Lead generated from cold calling campaign' },
      { date: '2026-06-18', action: 'Demo Conducted', user: 'P. Sharma', time: '11:00 AM', type: 'meeting', description: 'Full feature walkthrough. Strong interest in automation pipelines.' },
      { date: '2026-06-25', action: 'Proposal Shared', user: 'P. Sharma', time: '02:00 PM', type: 'email', description: 'Proposal and implementation schedule sent.' },
      { date: '2026-07-01', action: 'Stage changed to Negotiation', user: 'P. Sharma', time: '11:30 AM', type: 'system', description: 'Negotiating contract terms and final payment schedules' }
    ],
    isOverdue: false
  },
  {
    id: 5,
    createdAt: '2026-06-15T10:00:00Z',
    company: 'EcoLogistics',
    projectName: 'EcoLogistics Logistics Optimization Platform',
    contact: 'David Smith',
    stage: 'Prospecting',
    status: 'Contacted',
    value: '$30,000',
    industry: 'Logistics',
    size: '10-50',
    region: 'LATAM',
    priority: 'Low',
    owner: 'R. Nair',
    source: 'LinkedIn',
    score: 45,
    prob: 10,
    sentiment: 'Neutral',
    criteria: { bestTime: 'Morning (9 AM - 11 AM)', requirements: 'Need scalable transport tracking API' },
    altContact: { name: 'Maria Garcia', phone: '9554433221', email: 'maria.g@gmail.com' },
    productService: { products: ['Fleet Tracking API'], services: ['Implementation Support'] },
    requestType: { category: 'Product Request', type: 'Software License' },
    estDate: '2026-09-01',
    linkedin: { profile: 'linkedin.com/in/davidsmith', company: 'linkedin.com/company/ecolog' },
    commercial: { opportunities: 1, closingValue: '$30,000', estDealValue: '$3,000', valWithTax: '$35,400', valWithoutTax: '$30,000', commPercent: '5%', commAmount: '$1,500' },
    partners: ['Global Freight Partners'],
    history: [
      { date: '2026-06-15', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Lead created via automated marketing feed' },
      { date: '2026-06-20', action: 'Status changed to Contacted', user: 'R. Nair', time: '11:00 AM', type: 'call', description: 'Left a voicemail. Followed up with an email introduction.' }
    ],
    isOverdue: false
  },
  {
    id: 12,
    createdAt: '2026-06-12T09:00:00Z',
    company: 'GlobalTech Solutions',
    projectName: 'GlobalTech Solutions Cloud ERP Enablement',
    contact: 'Sarah Jenkins',
    stage: 'Proposal',
    status: 'Proposal Sent',
    value: '$150,000',
    industry: 'IT Services',
    size: '500+',
    region: 'Asia Pacific',
    priority: 'High',
    owner: 'D. Ghosh',
    source: 'Website',
    score: 80,
    prob: 60,
    sentiment: 'Positive',
    criteria: { bestTime: 'Afternoons (2 PM - 4 PM)', requirements: 'CRM upgrade to cloud version' },
    altContact: { name: 'Paul Allen', phone: '9443322110', email: 'paul.allen@gmail.com' },
    productService: { products: ['Cloud CRM Tier-1'], services: ['Onboarding Services'] },
    requestType: { category: 'Product Request', type: 'Cloud Subscription' },
    estDate: '2026-07-05', // Overdue by 2 days
    linkedin: { profile: 'linkedin.com/in/sarahjenkins', company: 'linkedin.com/company/globaltech' },
    commercial: { opportunities: 2, closingValue: '$150,000', estDealValue: '$90,000', valWithTax: '$177,000', valWithoutTax: '$150,000', commPercent: '10%', commAmount: '$15,000' },
    partners: [],
    history: [
      { date: '2026-06-12', action: 'Lead Created', user: 'System', time: '09:00 AM', type: 'system', description: 'Lead created from website demo request' },
      { date: '2026-06-15', action: 'Demo Conducted', user: 'D. Ghosh', time: '02:00 PM', type: 'meeting', description: 'Product demo completed. Detailed architecture overview requested.' },
      { date: '2026-06-28', action: 'Proposal Shared', user: 'D. Ghosh', time: '11:00 AM', type: 'email', description: 'Enterprise proposal shared. Review call scheduled.' }
    ],
    isOverdue: true
  },
  {
    id: 8,
    createdAt: '2026-06-10T10:30:00Z',
    company: 'Pinnacle Consulting',
    projectName: 'Pinnacle Consulting Client Engagement Suite',
    contact: 'Jane Smith',
    stage: 'Prospecting',
    status: 'Contacted',
    value: '$90,000',
    industry: 'Consulting',
    size: '100-500',
    region: 'Asia Pacific',
    priority: 'Medium',
    owner: 'S. Mishra',
    source: 'Referral',
    score: 70,
    prob: 20,
    sentiment: 'Neutral',
    criteria: { bestTime: 'Morning (9 AM - 11 AM)', requirements: 'Sales automation tools implementation' },
    altContact: { name: 'Tom Hardy', phone: '9332211009', email: 'tom.hardy@gmail.com' },
    productService: { products: ['SalesTracker Automations'], services: ['Training Services'] },
    requestType: { category: 'Product Request', type: 'Software Subscription' },
    estDate: '2026-09-15',
    linkedin: { profile: 'linkedin.com/company/pinnacle-consulting', company: 'linkedin.com/company/pinnacle-consulting' },
    commercial: { opportunities: 1, closingValue: '$90,000', estDealValue: '$18,000', valWithTax: '$106,200', valWithoutTax: '$90,000', commPercent: '10%', commAmount: '$9,000' },
    partners: [],
    history: [
      { date: '2026-06-10', action: 'Lead Created', user: 'System', time: '10:30 AM', type: 'system', description: 'Lead imported via referral form submission' },
      { date: '2026-06-15', action: 'Initial Contact', user: 'S. Mishra', time: '04:00 PM', type: 'call', description: 'Introductory call. The client requested a customized pricing model.' }
    ],
    isOverdue: false
  },
  {
    id: 23,
    createdAt: '2026-06-15T04:00:00Z',
    company: 'Acme Corp',
    projectName: 'Acme Corp Digital Transformation',
    contact: 'Sarah Jenkins',
    stage: 'Qualification',
    status: 'New',
    value: '$55,000',
    industry: 'Technology',
    size: '50-200',
    region: 'North America',
    priority: 'Medium',
    owner: 'H. Kumar',
    source: 'Website',
    score: 60,
    prob: 20,
    sentiment: 'Neutral',
    criteria: { bestTime: 'Anytime', requirements: 'Lead lifecycle custom templates setup' },
    altContact: { name: 'John Doe', phone: '9221100998', email: 'john.doe@gmail.com' },
    productService: { products: ['SalesTracker Standard'], services: ['Customization Package'] },
    requestType: { category: 'Product Request', type: 'Software License' },
    estDate: '2026-08-01',
    linkedin: { profile: 'linkedin.com/company/acme', company: 'linkedin.com/company/acme' },
    commercial: { opportunities: 1, closingValue: '$55,000', estDealValue: '$11,000', valWithTax: '$64,900', valWithoutTax: '$55,000', commPercent: '10%', commAmount: '$5,500' },
    partners: [],
    history: [
      { date: '2026-06-15', action: 'Lead Created', user: 'System', time: '04:00 PM', type: 'system', description: 'Inbound trial request created' }
    ],
    isOverdue: false
  },
  {
    id: 19,
    createdAt: '2026-06-14T17:30:00Z',
    company: 'Wayne Enterprises',
    projectName: 'Wayne Enterprises Digital Transformation',
    contact: 'David Miller',
    stage: 'Negotiation',
    status: 'Negotiation',
    value: '$190,000',
    industry: 'Defence',
    size: '500+',
    region: 'North America',
    priority: 'High',
    owner: 'P. Sharma',
    source: 'Website',
    score: 90,
    prob: 80,
    sentiment: 'Positive',
    criteria: { bestTime: 'Afternoons (2 PM - 4 PM)', requirements: 'Secure encrypted tracking systems' },
    altContact: { name: 'Lucius Fox', phone: '9110099887', email: 'lfox.wayne@gmail.com' },
    productService: { products: ['SalesTracker Secure Plus'], services: ['Security Integration'] },
    requestType: { category: 'Product Request', type: 'Enterprise Software' },
    estDate: '2026-07-02', // Overdue by 5 days
    linkedin: { profile: 'linkedin.com/company/wayne-enterprises', company: 'linkedin.com/company/wayne-enterprises' },
    commercial: { opportunities: 2, closingValue: '$190,000', estDealValue: '$152,000', valWithTax: '$224,200', valWithoutTax: '$190,000', commPercent: '10%', commAmount: '$19,000' },
    partners: [],
    history: [
      { date: '2026-06-14', action: 'Lead Created', user: 'System', time: '05:30 PM', type: 'system', description: 'Lead created via high-tier enterprise contact page' },
      { date: '2026-06-16', action: 'Initial Contact', user: 'P. Sharma', time: '10:00 AM', type: 'call', description: 'Established contact with Director of Procurement. Custom SLA needed.' },
      { date: '2026-06-25', action: 'Demo Conducted', user: 'P. Sharma', time: '03:00 PM', type: 'meeting', description: 'Conducted security framework demo with compliance lead' }
    ],
    isOverdue: true
  },
  {
    id: 30,
    createdAt: '2026-06-18T10:00:00Z',
    company: 'Stark Industries',
    projectName: 'Stark Industries Digital Transformation',
    contact: 'Pepper Potts',
    stage: 'Proposal',
    status: 'Proposal Sent',
    value: '$100,000',
    industry: 'Technology',
    size: '500+',
    region: 'North America',
    priority: 'High',
    owner: 'R. Nair',
    source: 'Referral',
    score: 85,
    prob: 50,
    sentiment: 'Positive',
    criteria: { bestTime: 'Morning (9 AM - 11 AM)', requirements: 'Automated workflow pipelines and custom templates' },
    altContact: { name: 'Happy Hogan', phone: '9998887776', email: 'happy@gmail.com' },
    productService: { products: ['SalesTracker Enterprise'], services: ['Custom SLA Integration'] },
    requestType: { category: 'Product Request', type: 'Enterprise CRM Software' },
    estDate: '2026-07-07', // Due Today
    linkedin: { profile: 'linkedin.com/company/stark-industries', company: 'linkedin.com/company/stark-industries' },
    commercial: { opportunities: 1, closingValue: '$100,000', estDealValue: '$50,000', valWithTax: '$118,000', valWithoutTax: '$100,000', commPercent: '10%', commAmount: '$10,000' },
    partners: [],
    history: [
      { date: '2026-06-18', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Lead imported via high-profile referral pipeline' },
      { date: '2026-06-22', action: 'Initial Contact', user: 'R. Nair', time: '11:00 AM', type: 'call', description: 'Discussion call completed. Proposal draft requested by end of month.' },
      { date: '2026-06-29', action: 'Proposal Shared', user: 'R. Nair', time: '02:00 PM', type: 'email', description: 'Sent detailed enterprise proposal with dynamic billing schedules' }
    ],
    isOverdue: false
  },
  
  // ─── ADDING WONS & LOSTS TO MEET PERCENTAGE AND HISTORICAL DISTRIBUTION ───
  {
    id: 1,
    createdAt: '2026-01-10T10:00:00Z',
    company: 'Initech',
    projectName: 'Initech Digital Transformation',
    contact: 'Peter Gibbons',
    stage: 'Closed Won',
    status: 'Won',
    value: '$350,000',
    industry: 'IT Services',
    size: '100-500',
    region: 'Asia Pacific',
    priority: 'Normal',
    owner: 'D. Ghosh',
    source: 'Website',
    score: 80,
    prob: 100,
    sentiment: 'Positive',
    criteria: { bestTime: 'Anytime', requirements: 'General consulting and platform licensing' },
    altContact: { name: 'Milton Waddams', phone: '9988776655', email: 'milton.w@gmail.com' },
    productService: { products: ['Consulting Pack A'], services: ['Custom Setup'] },
    requestType: { category: 'Consulting', type: 'SLA Support Integration' },
    estDate: '2026-01-15',
    linkedin: { profile: 'linkedin.com/company/initech', company: 'linkedin.com/company/initech' },
    commercial: { opportunities: 1, closingValue: '$350,000', estDealValue: '$350,000', valWithTax: '$413,000', valWithoutTax: '$350,000', commPercent: '10%', commAmount: '$35,000' },
    partners: [],
    history: [
      { date: '2026-01-10', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Inbound lead captured' },
      { date: '2026-01-15', action: 'Deal Won', user: 'D. Ghosh', time: '04:00 PM', type: 'system', description: 'Contract signed and payment received. SOW finalized.' }
    ],
    isOverdue: false
  },
  {
    id: 2,
    createdAt: '2026-03-01T10:00:00Z',
    company: 'Globex Inc',
    projectName: 'Globex Inc Digital Transformation',
    contact: 'Hank Scorpio',
    stage: 'Closed Won',
    status: 'Won',
    value: '$210,000',
    industry: 'Logistics',
    size: '500+',
    region: 'Europe',
    priority: 'High',
    owner: 'S. Mishra',
    source: 'LinkedIn',
    score: 90,
    prob: 100,
    sentiment: 'Positive',
    criteria: { bestTime: 'Anytime', requirements: 'Supply chain dashboard custom framework' },
    altContact: { name: 'Homer Simpson', phone: '9977553311', email: 'homer.simpson@gmail.com' },
    productService: { products: ['Logistics Pro Suite'], services: ['Premium SLA'] },
    requestType: { category: 'Enterprise Pack', type: 'Full Stack Deployment' },
    estDate: '2026-04-05',
    linkedin: { profile: 'linkedin.com/company/globex', company: 'linkedin.com/company/globex' },
    commercial: { opportunities: 1, closingValue: '$210,000', estDealValue: '$210,000', valWithTax: '$247,800', valWithoutTax: '$210,000', commPercent: '10%', commAmount: '$21,000' },
    partners: [],
    history: [
      { date: '2026-03-01', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'LinkedIn integration download' },
      { date: '2026-04-05', action: 'Deal Won', user: 'S. Mishra', time: '11:00 AM', type: 'system', description: 'Deal closed won. Onboarding started.' }
    ],
    isOverdue: false
  },
  {
    id: 3,
    createdAt: '2026-01-20T11:00:00Z',
    company: 'Acme Robotics',
    projectName: 'Acme Robotics Digital Transformation',
    contact: 'Jennifer Wu',
    stage: 'Closed Lost',
    status: 'Lost',
    value: '$120,000',
    industry: 'Manufacturing',
    size: '100-500',
    region: 'North America',
    priority: 'High',
    owner: 'H. Kumar',
    source: 'Cold Call',
    score: 50,
    prob: 0,
    sentiment: 'Negative',
    lostReason: 'Competitor Selected',
    criteria: { bestTime: 'Afternoon', requirements: 'Hardware assembly API interface' },
    altContact: { name: 'C3PO Robot', phone: '9888877777', email: 'c3po@gmail.com' },
    productService: { products: ['RoboLink Module'], services: ['Custom Setup'] },
    requestType: { category: 'Industrial Suite', type: 'Hardware Interface' },
    estDate: '2026-02-10',
    linkedin: { profile: 'linkedin.com/company/acme-robo', company: 'linkedin.com/company/acme-robo' },
    commercial: { opportunities: 1, closingValue: '$120,000', estDealValue: '$0', valWithTax: '$0', valWithoutTax: '$0', commPercent: '0%', commAmount: '$0' },
    partners: [],
    history: [
      { date: '2026-01-20', action: 'Lead Created', user: 'System', time: '11:00 AM', type: 'system', description: 'Ingested via outbound file upload' },
      { date: '2026-02-10', action: 'Deal Lost', user: 'H. Kumar', time: '05:00 PM', type: 'system', description: 'Deal marked lost. Client chose local low-cost competitor.' }
    ],
    isOverdue: false
  },
  {
    id: 4,
    createdAt: '2026-03-15T11:00:00Z',
    company: 'Nova Solutions',
    projectName: 'Nova Solutions Cloud ERP Enablement',
    contact: 'David Brown',
    stage: 'Closed Lost',
    status: 'Lost',
    value: '$80,000',
    industry: 'IT Services',
    size: '50-200',
    region: 'Europe',
    priority: 'Normal',
    owner: 'P. Sharma',
    source: 'Email Campaign',
    score: 40,
    prob: 0,
    sentiment: 'Negative',
    lostReason: 'Budget Constraints',
    criteria: { bestTime: 'Afternoon', requirements: 'Upgrade existing pipeline logs tools' },
    altContact: { name: 'Alice Smith', phone: '9777766666', email: 'alice.smith@gmail.com' },
    productService: { products: ['Pipeline Log Suite'], services: ['None'] },
    requestType: { category: 'Integration', type: 'Data Sync' },
    estDate: '2026-04-18',
    linkedin: { profile: 'linkedin.com/company/novasol', company: 'linkedin.com/company/novasol' },
    commercial: { opportunities: 1, closingValue: '$80,000', estDealValue: '$0', valWithTax: '$0', valWithoutTax: '$0', commPercent: '0%', commAmount: '$0' },
    partners: [],
    history: [
      { date: '2026-03-15', action: 'Lead Created', user: 'System', time: '11:00 AM', type: 'system', description: 'Outbound campaign click' },
      { date: '2026-04-18', action: 'Deal Lost', user: 'P. Sharma', time: '03:00 PM', type: 'system', description: 'Marked lost. Project cancelled due to Q2 budget constraints.' }
    ],
    isOverdue: false
  },
  {
    id: 6,
    createdAt: '2026-05-10T10:00:00Z',
    company: 'TechFlow Solutions',
    projectName: 'TechFlow Solutions Cloud ERP Enablement',
    contact: 'Amit Sharma',
    stage: 'Closed Lost',
    status: 'Lost',
    value: '$55,000',
    industry: 'Technology',
    size: '10-50',
    region: 'India',
    priority: 'Low',
    owner: 'R. Nair',
    source: 'Website',
    score: 42,
    prob: 0,
    sentiment: 'Negative',
    lostReason: 'No Response',
    criteria: { bestTime: 'Anytime', requirements: 'Local ticketing and automation framework' },
    altContact: { name: 'Rahul Varma', phone: '9666655555', email: 'rahul.varma@gmail.com' },
    productService: { products: ['Ticketing Engine Pro'], services: ['None'] },
    requestType: { category: 'Product License', type: 'Enterprise Standard' },
    estDate: '2026-06-04',
    linkedin: { profile: 'linkedin.com/company/techflow', company: 'linkedin.com/company/techflow' },
    commercial: { opportunities: 1, closingValue: '$55,000', estDealValue: '$0', valWithTax: '$0', valWithoutTax: '$0', commPercent: '0%', commAmount: '$0' },
    partners: [],
    history: [
      { date: '2026-05-10', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Inbound website request' },
      { date: '2026-06-04', action: 'Deal Lost', user: 'R. Nair', time: '11:00 AM', type: 'system', description: 'Marked lost. Client stopped responding to follow-up campaigns.' }
    ],
    isOverdue: false
  },
  
  // ─── HISTORICAL WON DEALS FOR CHART & DURATION ANALYSIS ───
  {
    id: 46,
    createdAt: '2026-02-15T09:00:00Z',
    company: 'Apollo Healthcare',
    projectName: 'Apollo Healthcare Patient Data Modernization',
    contact: 'Dr. Rajendra Prasad',
    stage: 'Closed Won',
    status: 'Won',
    value: '$180,000',
    industry: 'Healthcare',
    size: '500+',
    region: 'India',
    priority: 'High',
    owner: 'D. Ghosh',
    source: 'Partner',
    score: 95,
    prob: 100,
    sentiment: 'Positive',
    criteria: { bestTime: 'Afternoon', requirements: 'Patient lifecycle monitoring integration' },
    altContact: { name: 'Kiran Reddy', phone: '9555544444', email: 'kiran.r@gmail.com' },
    productService: { products: ['Healthcare Suite V2'], services: ['24/7 Gold Support'] },
    requestType: { category: 'Enterprise Solution', type: 'Custom Implementation' },
    estDate: '2026-03-25',
    linkedin: { profile: 'linkedin.com/company/apollo-health', company: 'linkedin.com/company/apollo-health' },
    commercial: { opportunities: 1, closingValue: '$180,000', estDealValue: '$180,000', valWithTax: '$212,400', valWithoutTax: '$180,000', commPercent: '10%', commAmount: '$18,000' },
    partners: ['Apollo Networks'],
    history: [
      { date: '2026-02-15', action: 'Lead Created', user: 'System', time: '09:00 AM', type: 'system', description: 'Partner lead registration' },
      { date: '2026-03-25', action: 'Deal Won', user: 'D. Ghosh', time: '04:30 PM', type: 'system', description: 'Sales agreement signed by CEO' }
    ],
    isOverdue: false
  },
  {
    id: 47,
    createdAt: '2026-03-10T10:00:00Z',
    company: 'Metro Retail Group',
    projectName: 'Metro Retail Group Omnichannel Commerce Transformation',
    contact: 'Sunita Narain',
    stage: 'Closed Won',
    status: 'Won',
    value: '$95,000',
    industry: 'Retail',
    size: '100-500',
    region: 'India',
    priority: 'Normal',
    owner: 'S. Mishra',
    source: 'Website',
    score: 88,
    prob: 100,
    sentiment: 'Positive',
    criteria: { bestTime: 'Morning', requirements: 'POS billing terminal automated feeds' },
    altContact: { name: 'Vijay Shekhar', phone: '9444433333', email: 'vijay.s@gmail.com' },
    productService: { products: ['POS Billings Premium'], services: ['Hardware Sync'] },
    requestType: { category: 'Product Suite', type: 'Retail System' },
    estDate: '2026-04-10',
    linkedin: { profile: 'linkedin.com/company/metro-retail', company: 'linkedin.com/company/metro-retail' },
    commercial: { opportunities: 1, closingValue: '$95,000', estDealValue: '$95,000', valWithTax: '$112,100', valWithoutTax: '$95,000', commPercent: '10%', commAmount: '$9,500' },
    partners: [],
    history: [
      { date: '2026-03-10', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Website inbound lead' },
      { date: '2026-04-10', action: 'Deal Won', user: 'S. Mishra', time: '03:15 PM', type: 'system', description: 'Invoiced and closed won' }
    ],
    isOverdue: false
  },
  {
    id: 48,
    createdAt: '2026-04-05T14:00:00Z',
    company: 'Prime Banking Corp',
    projectName: 'Prime Banking Corp Risk & Compliance Modernization',
    contact: 'Venkatesh Iyer',
    stage: 'Closed Won',
    status: 'Won',
    value: '$280,000',
    industry: 'Banking',
    size: '500+',
    region: 'India',
    priority: 'Urgent',
    owner: 'H. Kumar',
    source: 'Partner',
    score: 97,
    prob: 100,
    sentiment: 'Positive',
    criteria: { bestTime: 'Afternoon', requirements: 'Encrypted banking backend audit log platform' },
    altContact: { name: 'Karthik Raja', phone: '9333322222', email: 'karthik.r@gmail.com' },
    productService: { products: ['Banking Security Core'], services: ['Deployment Package'] },
    requestType: { category: 'FinTech Enterprise', type: 'Dedicated Deploy' },
    estDate: '2026-05-15',
    linkedin: { profile: 'linkedin.com/company/prime-bank', company: 'linkedin.com/company/prime-bank' },
    commercial: { opportunities: 2, closingValue: '$280,000', estDealValue: '$280,000', valWithTax: '$330,400', valWithoutTax: '$280,000', commPercent: '10%', commAmount: '$28,000' },
    partners: [],
    history: [
      { date: '2026-04-05', action: 'Lead Created', user: 'System', time: '02:00 PM', type: 'system', description: 'Partner registration from Prime networks' },
      { date: '2026-05-15', action: 'Deal Won', user: 'H. Kumar', time: '06:00 PM', type: 'system', description: 'Contracts signed and verified' }
    ],
    isOverdue: false
  },
  {
    id: 49,
    createdAt: '2026-04-12T10:00:00Z',
    company: 'Blue Chip Finance',
    projectName: 'Blue Chip Finance Risk & Compliance Modernization',
    contact: 'Amitabh Bachchan',
    stage: 'Closed Won',
    status: 'Won',
    value: '$150,000',
    industry: 'Finance',
    size: '100-500',
    region: 'India',
    priority: 'High',
    owner: 'P. Sharma',
    source: 'Referral',
    score: 93,
    prob: 100,
    sentiment: 'Positive',
    criteria: { bestTime: 'Morning', requirements: 'Investment modeling dashboard' },
    altContact: { name: 'Abhishek B', phone: '9222211111', email: 'abhishek@gmail.com' },
    productService: { products: ['Finance Pro Package'], services: ['Consulting SLA'] },
    requestType: { category: 'FinTech CRM', type: 'Enterprise Platform' },
    estDate: '2026-05-20',
    linkedin: { profile: 'linkedin.com/company/bluechip-finance', company: 'linkedin.com/company/bluechip-finance' },
    commercial: { opportunities: 1, closingValue: '$150,000', estDealValue: '$150,000', valWithTax: '$177,000', valWithoutTax: '$150,000', commPercent: '10%', commAmount: '$15,000' },
    partners: [],
    history: [
      { date: '2026-04-12', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Referral registration' },
      { date: '2026-05-20', action: 'Deal Won', user: 'P. Sharma', time: '02:00 PM', type: 'system', description: 'Sales completed successfully' }
    ],
    isOverdue: false
  },
  {
    id: 50,
    createdAt: '2026-05-01T15:00:00Z',
    company: 'Green Logistics Solutions',
    projectName: 'Green Logistics Solutions Cloud ERP Enablement',
    contact: 'Nisha Pillai',
    stage: 'Closed Won',
    status: 'Won',
    value: '$75,000',
    industry: 'Logistics',
    size: '50-200',
    region: 'India',
    priority: 'Normal',
    owner: 'R. Nair',
    source: 'Google Ads',
    score: 82,
    prob: 100,
    sentiment: 'Positive',
    criteria: { bestTime: 'Afternoon', requirements: 'Carbon footprint analytics API' },
    altContact: { name: 'Sanjay Dutt', phone: '9111100000', email: 'sanjay.d@gmail.com' },
    productService: { products: ['Carbon Tracker API'], services: ['None'] },
    requestType: { category: 'Product Request', type: 'API License' },
    estDate: '2026-06-05',
    linkedin: { profile: 'linkedin.com/company/greenlogistics', company: 'linkedin.com/company/greenlogistics' },
    commercial: { opportunities: 1, closingValue: '$75,000', estDealValue: '$75,000', valWithTax: '$88,500', valWithoutTax: '$75,000', commPercent: '10%', commAmount: '$7,500' },
    partners: [],
    history: [
      { date: '2026-05-01', action: 'Lead Created', user: 'System', time: '03:00 PM', type: 'system', description: 'Inbound Google Ads lead' },
      { date: '2026-06-05', action: 'Deal Won', user: 'R. Nair', time: '04:15 PM', type: 'system', description: 'Payment completed won' }
    ],
    isOverdue: false
  },

  // ─── ADDING ADDITIONAL REALISTIC LEADS TO REACH 85+ RECORDS ───
  {
    id: 51, createdAt: '2026-06-01T09:00:00Z', company: 'Apex Real Estate', contact: 'Vijay Mallya',
    stage: 'Prospecting', status: 'New', value: '$65,000', industry: 'Real Estate', size: '50-200',
    region: 'India', priority: 'Medium', owner: 'D. Ghosh', source: 'Google Ads', score: 68, prob: 10,
    sentiment: 'Neutral', criteria: { bestTime: 'Morning', requirements: 'CRM property sales modules setup' },
    altContact: { name: 'Siddharth M', phone: '9900887766', email: 'siddharth@gmail.com' },
    productService: { products: ['SalesTracker RealEstate Pack'], services: ['None'] },
    requestType: { category: 'Product Request', type: 'Software License' },
    estDate: '2026-09-10',
    linkedin: { profile: 'linkedin.com/company/apex-re', company: 'linkedin.com/company/apex-re' },
    commercial: { opportunities: 1, closingValue: '$65,000', estDealValue: '$6,500', valWithTax: '$76,700', valWithoutTax: '$65,000', commPercent: '10%', commAmount: '$6,500' },
    partners: [],
    history: [{ date: '2026-06-01', action: 'Lead Created', user: 'System', time: '09:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 52, createdAt: '2026-06-02T10:00:00Z', company: 'Indus Healthcare', contact: 'Naresh Trehan',
    stage: 'Qualification', status: 'Contacted', value: '$110,000', industry: 'Healthcare', size: '100-500',
    region: 'India', priority: 'High', owner: 'S. Mishra', source: 'LinkedIn', score: 79, prob: 20,
    sentiment: 'Positive', criteria: { bestTime: 'Afternoon', requirements: 'Electronic health record analytics integration' },
    altContact: { name: 'Geeta Trehan', phone: '9988771122', email: 'geeta@gmail.com' },
    productService: { products: ['EHR Analytics Suite'], services: ['Premium Integration'] },
    requestType: { category: 'Enterprise Package', type: 'Dedicated Deploy' },
    estDate: '2026-08-20',
    linkedin: { profile: 'linkedin.com/company/indus-health', company: 'linkedin.com/company/indus-health' },
    commercial: { opportunities: 1, closingValue: '$110,000', estDealValue: '$22,000', valWithTax: '$129,800', valWithoutTax: '$110,000', commPercent: '10%', commAmount: '$11,000' },
    partners: [],
    history: [{ date: '2026-06-02', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 53, createdAt: '2026-06-03T11:00:00Z', company: 'Tata Steel Corp', contact: 'Ratan Tata',
    stage: 'Needs Analysis', status: 'Follow-up', value: '$320,000', industry: 'Manufacturing', size: '500+',
    region: 'India', priority: 'Urgent', owner: 'H. Kumar', source: 'Partner', score: 94, prob: 30,
    sentiment: 'Positive', criteria: { bestTime: 'Morning', requirements: 'Supply automation workflow engine and CRM dashboards' },
    altContact: { name: 'Cyrus Mistry', phone: '9988112233', email: 'cyrus@gmail.com' },
    productService: { products: ['Tata Steel CRM Custom Pack'], services: ['Onsite Support Package'] },
    requestType: { category: 'Custom Solutions', type: 'Full Deployment' },
    estDate: '2026-07-06', // Overdue by 1 day
    linkedin: { profile: 'linkedin.com/company/tata-steel', company: 'linkedin.com/company/tata-steel' },
    commercial: { opportunities: 2, closingValue: '$320,000', estDealValue: '$96,000', valWithTax: '$377,600', valWithoutTax: '$320,000', commPercent: '10%', commAmount: '$32,000' },
    partners: ['Tata Consultancy'],
    history: [{ date: '2026-06-03', action: 'Lead Created', user: 'System', time: '11:00 AM', type: 'system', description: 'Created' }],
    isOverdue: true
  },
  {
    id: 54, createdAt: '2026-06-04T12:00:00Z', company: 'HDFC Security', contact: 'Aditya Puri',
    stage: 'Proposal', status: 'Proposal Sent', value: '$180,000', industry: 'Banking', size: '500+',
    region: 'India', priority: 'High', owner: 'P. Sharma', source: 'Referral', score: 87, prob: 60,
    sentiment: 'Positive', criteria: { bestTime: 'Anytime', requirements: 'Financial secure gateway connections' },
    altContact: { name: 'Shyam Puria', phone: '9977885566', email: 'shyam@gmail.com' },
    productService: { products: ['FinSec Shield Core'], services: ['Deployment Consultancy'] },
    requestType: { category: 'Product Request', type: 'FinTech Subscription' },
    estDate: '2026-07-05', // Overdue by 2 days
    linkedin: { profile: 'linkedin.com/company/hdfc-sec', company: 'linkedin.com/company/hdfc-sec' },
    commercial: { opportunities: 1, closingValue: '$180,000', estDealValue: '$108,000', valWithTax: '$212,400', valWithoutTax: '$180,000', commPercent: '10%', commAmount: '$18,000' },
    partners: [],
    history: [{ date: '2026-06-04', action: 'Lead Created', user: 'System', time: '12:00 PM', type: 'system', description: 'Created' }],
    isOverdue: true
  },
  {
    id: 55, createdAt: '2026-06-05T13:00:00Z', company: 'Reliance Retail Ltd', contact: 'Mukesh Ambani',
    stage: 'Negotiation', status: 'Negotiation', value: '$295,000', industry: 'Retail', size: '500+',
    region: 'India', priority: 'Urgent', owner: 'R. Nair', source: 'LinkedIn', score: 98, prob: 80,
    sentiment: 'Interested', criteria: { bestTime: 'Afternoon', requirements: 'Multi-store billing integration engine' },
    altContact: { name: 'Isha Ambani', phone: '9900115599', email: 'isha@gmail.com' },
    productService: { products: ['Retail Core Pro Plus'], services: ['DevOps Onboarding Services'] },
    requestType: { category: 'Product Request', type: 'Enterprise Platform' },
    estDate: '2026-07-07', // Due Today
    linkedin: { profile: 'linkedin.com/company/reliance-retail', company: 'linkedin.com/company/reliance-retail' },
    commercial: { opportunities: 2, closingValue: '$295,000', estDealValue: '$236,000', valWithTax: '$348,100', valWithoutTax: '$295,000', commPercent: '10%', commAmount: '$29,500' },
    partners: [],
    history: [{ date: '2026-06-05', action: 'Lead Created', user: 'System', time: '01:00 PM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  
  // ─── ACTIVE PIPELINE EXPANSION (LEADS 56-85 TO FILL CHARTS BEAUTIFULLY) ───
  {
    id: 56, createdAt: '2026-06-06T09:00:00Z', company: 'Flipkart Logistics', contact: 'Kalyan Krishnamurthy',
    stage: 'Needs Analysis', status: 'Contacted', value: '$115,000', industry: 'Logistics', size: '500+',
    region: 'India', priority: 'High', owner: 'D. Ghosh', source: 'Facebook Ads', score: 81, prob: 30,
    sentiment: 'Positive', criteria: { bestTime: 'Morning', requirements: 'Last mile tracking routing API' },
    altContact: { name: 'Sachin Bansal', phone: '9888877711', email: 'sachin.b@gmail.com' },
    productService: { products: ['LastMile Route API'], services: ['API Configuration Package'] },
    requestType: { category: 'Product Request', type: 'API Subscription' },
    estDate: '2026-08-15',
    linkedin: { profile: 'linkedin.com/company/flipkart', company: 'linkedin.com/company/flipkart' },
    commercial: { opportunities: 1, closingValue: '$115,000', estDealValue: '$34,500', valWithTax: '$135,700', valWithoutTax: '$115,000', commPercent: '10%', commAmount: '$11,500' },
    partners: [],
    history: [{ date: '2026-06-06', action: 'Lead Created', user: 'System', time: '09:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 57, createdAt: '2026-06-07T10:00:00Z', company: 'Delhivery Logistics', contact: 'Sahil Barua',
    stage: 'Prospecting', status: 'New', value: '$85,000', industry: 'Logistics', size: '500+',
    region: 'India', priority: 'Medium', owner: 'S. Mishra', source: 'Google Ads', score: 72, prob: 10,
    sentiment: 'Neutral', criteria: { bestTime: 'Afternoon', requirements: 'Fleet dashboard custom templates setup' },
    altContact: { name: 'Mohit Tandon', phone: '9777788811', email: 'mohit@gmail.com' },
    productService: { products: ['Fleet Logistics Suite'], services: ['Implementation Pack'] },
    requestType: { category: 'Product Request', type: 'Software License' },
    estDate: '2026-09-01',
    linkedin: { profile: 'linkedin.com/company/delhivery', company: 'linkedin.com/company/delhivery' },
    commercial: { opportunities: 1, closingValue: '$85,000', estDealValue: '$8,500', valWithTax: '$100,300', valWithoutTax: '$85,000', commPercent: '10%', commAmount: '$8,500' },
    partners: [],
    history: [{ date: '2026-06-07', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 58, createdAt: '2026-06-08T11:00:00Z', company: 'Byjus Education', contact: 'Byju Raveendran',
    stage: 'Proposal', status: 'Proposal Sent', value: '$95,000', industry: 'Education', size: '100-500',
    region: 'India', priority: 'Normal', owner: 'H. Kumar', source: 'Website', score: 68, prob: 50,
    sentiment: 'Neutral', criteria: { bestTime: 'Morning', requirements: 'LMS dashboard customized billing pipeline' },
    altContact: { name: 'Divya Gokulnath', phone: '9666655511', email: 'divya@gmail.com' },
    productService: { products: ['LMS Custom Billing Platform'], services: ['Onboarding Services'] },
    requestType: { category: 'Product Request', type: 'LMS Platform' },
    estDate: '2026-07-06', // Overdue by 1 day
    linkedin: { profile: 'linkedin.com/company/byjus', company: 'linkedin.com/company/byjus' },
    commercial: { opportunities: 1, closingValue: '$95,000', estDealValue: '$47,500', valWithTax: '$112,100', valWithoutTax: '$95,000', commPercent: '10%', commAmount: '$9,500' },
    partners: [],
    history: [{ date: '2026-06-08', action: 'Lead Created', user: 'System', time: '11:00 AM', type: 'system', description: 'Created' }],
    isOverdue: true
  },
  {
    id: 59, createdAt: '2026-06-09T12:00:00Z', company: 'Unacademy Academy', contact: 'Gaurav Munjal',
    stage: 'Needs Analysis', status: 'Contacted', value: '$110,000', industry: 'Education', size: '100-500',
    region: 'India', priority: 'Medium', owner: 'P. Sharma', source: 'LinkedIn', score: 76, prob: 30,
    sentiment: 'Positive', criteria: { bestTime: 'Afternoon', requirements: 'Secure encrypted test delivery server connection' },
    altContact: { name: 'Roman Saini', phone: '9555544411', email: 'roman@gmail.com' },
    productService: { products: ['Secure Test Platform Core'], services: ['Setup Support Pack'] },
    requestType: { category: 'Product Request', type: 'Platform Subscription' },
    estDate: '2026-08-25',
    linkedin: { profile: 'linkedin.com/company/unacademy', company: 'linkedin.com/company/unacademy' },
    commercial: { opportunities: 1, closingValue: '$110,000', estDealValue: '$33,000', valWithTax: '$129,800', valWithoutTax: '$110,000', commPercent: '10%', commAmount: '$11,000' },
    partners: [],
    history: [{ date: '2026-06-09', action: 'Lead Created', user: 'System', time: '12:00 PM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 60, createdAt: '2026-06-10T13:00:00Z', company: 'Vedantu Class', contact: 'Vamsi Krishna',
    stage: 'Qualification', status: 'New', value: '$65,000', industry: 'Education', size: '50-200',
    region: 'India', priority: 'Low', owner: 'R. Nair', source: 'Email Campaign', score: 58, prob: 20,
    sentiment: 'Neutral', criteria: { bestTime: 'Anytime', requirements: 'LMS interactive class dashboards' },
    altContact: { name: 'Pulkit Jain', phone: '9444433311', email: 'pulkit@gmail.com' },
    productService: { products: ['LMS Interactive Suite'], services: ['None'] },
    requestType: { category: 'Product Request', type: 'LMS License' },
    estDate: '2026-09-12',
    linkedin: { profile: 'linkedin.com/company/vedantu', company: 'linkedin.com/company/vedantu' },
    commercial: { opportunities: 1, closingValue: '$65,000', estDealValue: '$13,000', valWithTax: '$76,700', valWithoutTax: '$65,000', commPercent: '10%', commAmount: '$6,500' },
    partners: [],
    history: [{ date: '2026-06-10', action: 'Lead Created', user: 'System', time: '01:00 PM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 61, createdAt: '2026-06-11T09:00:00Z', company: 'Zomato Food Delivery', contact: 'Deepinder Goyal',
    stage: 'Negotiation', status: 'Negotiation', value: '$230,000', industry: 'E-commerce', size: '500+',
    region: 'India', priority: 'High', owner: 'D. Ghosh', source: 'LinkedIn', score: 95, prob: 80,
    sentiment: 'Interested', criteria: { bestTime: 'Afternoon', requirements: 'Merchant billing automation backend' },
    altContact: { name: 'Gaurav Gupta', phone: '9333322211', email: 'gaurav.g@gmail.com' },
    productService: { products: ['Merchant Sync API Plus'], services: ['API Deployment Package'] },
    requestType: { category: 'Product Request', type: 'Enterprise API' },
    estDate: '2026-07-08', // Due Tomorrow
    linkedin: { profile: 'linkedin.com/company/zomato', company: 'linkedin.com/company/zomato' },
    commercial: { opportunities: 2, closingValue: '$230,000', estDealValue: '$184,000', valWithTax: '$271,400', valWithoutTax: '$230,000', commPercent: '10%', commAmount: '$23,000' },
    partners: [],
    history: [{ date: '2026-06-11', action: 'Lead Created', user: 'System', time: '09:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 62, createdAt: '2026-06-12T10:00:00Z', company: 'Swiggy Munchies', contact: 'Sriharsha Majety',
    stage: 'Needs Analysis', status: 'Contacted', value: '$195,000', industry: 'E-commerce', size: '500+',
    region: 'India', priority: 'High', owner: 'S. Mishra', source: 'Referral', score: 86, prob: 40,
    sentiment: 'Positive', criteria: { bestTime: 'Morning', requirements: 'Hyperlocal delivery route configuration backend' },
    altContact: { name: 'Nandan Reddy', phone: '9222211100', email: 'nandan@gmail.com' },
    productService: { products: ['Hyperlocal Routing Suite'], services: ['Setup Support Pack'] },
    requestType: { category: 'Product Request', type: 'Enterprise Software' },
    estDate: '2026-08-10',
    linkedin: { profile: 'linkedin.com/company/swiggy', company: 'linkedin.com/company/swiggy' },
    commercial: { opportunities: 1, closingValue: '$195,000', estDealValue: '$78,000', valWithTax: '$230,100', valWithoutTax: '$195,000', commPercent: '10%', commAmount: '$19,500' },
    partners: [],
    history: [{ date: '2026-06-12', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 63, createdAt: '2026-06-13T11:00:00Z', company: 'Nykaa Beauty Stores', contact: 'Falguni Nayar',
    stage: 'Proposal', status: 'Proposal Sent', value: '$105,000', industry: 'E-commerce', size: '100-500',
    region: 'India', priority: 'Medium', owner: 'H. Kumar', source: 'Website', score: 79, prob: 50,
    sentiment: 'Positive', criteria: { bestTime: 'Afternoon', requirements: 'Omnichannel inventory dashboard' },
    altContact: { name: 'Adwaita Nayar', phone: '9111100099', email: 'adwaita@gmail.com' },
    productService: { products: ['Nykaa Inventory Engine'], services: ['Custom Setup Consulting'] },
    requestType: { category: 'Product Request', type: 'Omnichannel Platform' },
    estDate: '2026-07-06', // Overdue by 1 day
    linkedin: { profile: 'linkedin.com/company/nykaa', company: 'linkedin.com/company/nykaa' },
    commercial: { opportunities: 1, closingValue: '$105,000', estDealValue: '$52,500', valWithTax: '$123,900', valWithoutTax: '$105,000', commPercent: '10%', commAmount: '$10,500' },
    partners: [],
    history: [{ date: '2026-06-13', action: 'Lead Created', user: 'System', time: '11:00 AM', type: 'system', description: 'Created' }],
    isOverdue: true
  },
  {
    id: 64, createdAt: '2026-06-14T12:00:00Z', company: 'Lenskart Vision', contact: 'Peyush Bansal',
    stage: 'Prospecting', status: 'New', value: '$75,000', industry: 'E-commerce', size: '100-500',
    region: 'India', priority: 'Normal', owner: 'P. Sharma', source: 'Cold Call', score: 62, prob: 15,
    sentiment: 'Neutral', criteria: { bestTime: 'Morning', requirements: 'Automated prescription sync server' },
    altContact: { name: 'Amit Chaudhary', phone: '9900881122', email: 'amit@gmail.com' },
    productService: { products: ['Prescription Sync Server'], services: ['API configuration Package'] },
    requestType: { category: 'Product Request', type: 'Software license' },
    estDate: '2026-09-30',
    linkedin: { profile: 'linkedin.com/company/lenskart', company: 'linkedin.com/company/lenskart' },
    commercial: { opportunities: 1, closingValue: '$75,000', estDealValue: '$11,250', valWithTax: '$88,500', valWithoutTax: '$75,000', commPercent: '10%', commAmount: '$7,500' },
    partners: [],
    history: [{ date: '2026-06-14', action: 'Lead Created', user: 'System', time: '12:00 PM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 65, createdAt: '2026-06-15T13:00:00Z', company: 'Paytm Payments', contact: 'Vijay Shekhar Sharma',
    stage: 'Negotiation', status: 'Negotiation', value: '$340,000', industry: 'Banking', size: '500+',
    region: 'India', priority: 'Urgent', owner: 'R. Nair', source: 'LinkedIn', score: 97, prob: 80,
    sentiment: 'Interested', criteria: { bestTime: 'Afternoon', requirements: 'FinTech security logging module' },
    altContact: { name: 'Madhur Deora', phone: '9877665511', email: 'madhur@gmail.com' },
    productService: { products: ['FinTech Audit Core Engine'], services: ['Dedicated Onsite Setup'] },
    requestType: { category: 'Product Request', type: 'FinTech Platform' },
    estDate: '2026-07-07', // Due Today
    linkedin: { profile: 'linkedin.com/company/paytm', company: 'linkedin.com/company/paytm' },
    commercial: { opportunities: 2, closingValue: '$340,000', estDealValue: '$272,000', valWithTax: '$401,200', valWithoutTax: '$340,000', commPercent: '10%', commAmount: '$34,000' },
    partners: [],
    history: [{ date: '2026-06-15', action: 'Lead Created', user: 'System', time: '01:00 PM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 66, createdAt: '2026-06-16T09:00:00Z', company: 'DLF Real Estate', contact: 'Rajiv Singh',
    stage: 'Prospecting', status: 'New', value: '$95,000', industry: 'Real Estate', size: '500+',
    region: 'India', priority: 'Medium', owner: 'D. Ghosh', source: 'Partner', score: 71, prob: 10,
    sentiment: 'Neutral', criteria: { bestTime: 'Morning', requirements: 'CRM property sales backend system' },
    altContact: { name: 'Devinder Singh', phone: '9766554411', email: 'devinder@gmail.com' },
    productService: { products: ['SalesTracker RealEstate Pro'], services: ['None'] },
    requestType: { category: 'Product Request', type: 'Software license' },
    estDate: '2026-09-25',
    linkedin: { profile: 'linkedin.com/company/dlf', company: 'linkedin.com/company/dlf' },
    commercial: { opportunities: 1, closingValue: '$95,000', estDealValue: '$9,500', valWithTax: '$112,100', valWithoutTax: '$95,000', commPercent: '10%', commAmount: '$9,500' },
    partners: [],
    history: [{ date: '2026-06-16', action: 'Lead Created', user: 'System', time: '09:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 67, createdAt: '2026-06-17T10:00:00Z', company: 'Godrej Properties', contact: 'Pirojsha Godrej',
    stage: 'Needs Analysis', status: 'Contacted', value: '$135,000', industry: 'Real Estate', size: '100-500',
    region: 'India', priority: 'High', owner: 'S. Mishra', source: 'Website', score: 82, prob: 30,
    sentiment: 'Positive', criteria: { bestTime: 'Afternoon', requirements: 'Client scheduling and monitoring backend dashboard' },
    altContact: { name: 'Mohit Malhotra', phone: '9655443311', email: 'mohit.m@gmail.com' },
    productService: { products: ['SalesTracker Scheduling Hub'], services: ['Implementation Package'] },
    requestType: { category: 'Product Request', type: 'Enterprise Platform' },
    estDate: '2026-08-20',
    linkedin: { profile: 'linkedin.com/company/godrej-properties', company: 'linkedin.com/company/godrej-properties' },
    commercial: { opportunities: 1, closingValue: '$135,000', estDealValue: '$40,500', valWithTax: '$159,300', valWithoutTax: '$135,000', commPercent: '10%', commAmount: '$13,500' },
    partners: [],
    history: [{ date: '2026-06-17', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 68, createdAt: '2026-06-18T11:00:00Z', company: 'L&T Infotech', contact: 'Sanjay Jalona',
    stage: 'Proposal', status: 'Proposal Sent', value: '$220,000', industry: 'IT Services', size: '500+',
    region: 'India', priority: 'High', owner: 'H. Kumar', source: 'LinkedIn', score: 89, prob: 60,
    sentiment: 'Positive', criteria: { bestTime: 'Anytime', requirements: 'Audit log security module deployment' },
    altContact: { name: 'Sudip Banerjee', phone: '9544332211', email: 'sudip@gmail.com' },
    productService: { products: ['Audit Log Security Module'], services: ['DevOps configuration Package'] },
    requestType: { category: 'Product Request', type: 'Enterprise Platform' },
    estDate: '2026-07-06', // Overdue by 1 day
    linkedin: { profile: 'linkedin.com/company/lti', company: 'linkedin.com/company/lti' },
    commercial: { opportunities: 2, closingValue: '$220,000', estDealValue: '$132,000', valWithTax: '$259,600', valWithoutTax: '$220,000', commPercent: '10%', commAmount: '$22,000' },
    partners: [],
    history: [{ date: '2026-06-18', action: 'Lead Created', user: 'System', time: '11:00 AM', type: 'system', description: 'Created' }],
    isOverdue: true
  },
  {
    id: 69, createdAt: '2026-06-19T12:00:00Z', company: 'Wipro Technologies', contact: 'Thierry Delaporte',
    stage: 'Negotiation', status: 'Negotiation', value: '$280,000', industry: 'IT Services', size: '500+',
    region: 'India', priority: 'Urgent', owner: 'P. Sharma', source: 'Referral', score: 94, prob: 90,
    sentiment: 'Interested', criteria: { bestTime: 'Afternoon', requirements: 'CRM platform multi-regional setup' },
    altContact: { name: 'Rishad Premji', phone: '9433221100', email: 'rishad@gmail.com' },
    productService: { products: ['SalesTracker Global Enterprise'], services: ['Global Deployment Package'] },
    requestType: { category: 'Product Request', type: 'Enterprise Software' },
    estDate: '2026-07-08', // Due Tomorrow
    linkedin: { profile: 'linkedin.com/company/wipro', company: 'linkedin.com/company/wipro' },
    commercial: { opportunities: 3, closingValue: '$280,000', estDealValue: '$252,000', valWithTax: '$330,400', valWithoutTax: '$280,000', commPercent: '10%', commAmount: '$28,000' },
    partners: [],
    history: [{ date: '2026-06-19', action: 'Lead Created', user: 'System', time: '12:00 PM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 70, createdAt: '2026-06-20T13:00:00Z', company: 'Mindtree Consulting', contact: 'Debashis Chatterjee',
    stage: 'Needs Analysis', status: 'Contacted', value: '$140,000', industry: 'IT Services', size: '500+',
    region: 'India', priority: 'Medium', owner: 'R. Nair', source: 'Website', score: 79, prob: 30,
    sentiment: 'Neutral', criteria: { bestTime: 'Morning', requirements: 'Ticketing workflow engine configuration' },
    altContact: { name: 'Rostow Ravanan', phone: '9322110099', email: 'rostow@gmail.com' },
    productService: { products: ['Ticketing Workflow Engine'], services: ['Onboarding Services'] },
    requestType: { category: 'Product Request', type: 'Enterprise Platform' },
    estDate: '2026-08-30',
    linkedin: { profile: 'linkedin.com/company/mindtree', company: 'linkedin.com/company/mindtree' },
    commercial: { opportunities: 1, closingValue: '$140,000', estDealValue: '$42,000', valWithTax: '$165,200', valWithoutTax: '$140,000', commPercent: '10%', commAmount: '$14,000' },
    partners: [],
    history: [{ date: '2026-06-20', action: 'Lead Created', user: 'System', time: '01:00 PM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 71, createdAt: '2026-06-21T09:00:00Z', company: 'Fortis Hospital Group', contact: 'Dr. Ashutosh Raghuvanshi',
    stage: 'Qualification', status: 'New', value: '$95,000', industry: 'Healthcare', size: '500+',
    region: 'India', priority: 'High', owner: 'D. Ghosh', source: 'LinkedIn', score: 77, prob: 20,
    sentiment: 'Positive', criteria: { bestTime: 'Afternoon', requirements: 'Patient booking tracking system license' },
    altContact: { name: 'Aditya Vij', phone: '9211009988', email: 'aditya.vij@gmail.com' },
    productService: { products: ['Patient Tracking License'], services: ['None'] },
    requestType: { category: 'Product Request', type: 'Software License' },
    estDate: '2026-08-15',
    linkedin: { profile: 'linkedin.com/company/fortis-healthcare', company: 'linkedin.com/company/fortis-healthcare' },
    commercial: { opportunities: 1, closingValue: '$95,000', estDealValue: '$19,000', valWithTax: '$112,100', valWithoutTax: '$95,000', commPercent: '10%', commAmount: '$9,500' },
    partners: [],
    history: [{ date: '2026-06-21', action: 'Lead Created', user: 'System', time: '09:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 72, createdAt: '2026-06-22T10:00:00Z', company: 'Max Healthcare Ltd', contact: 'Abhay Soi',
    stage: 'Proposal', status: 'Proposal Sent', value: '$165,000', industry: 'Healthcare', size: '500+',
    region: 'India', priority: 'High', owner: 'S. Mishra', source: 'Trade Show', score: 86, prob: 50,
    sentiment: 'Positive', criteria: { bestTime: 'Morning', requirements: 'Central database syncing EHR module setup' },
    altContact: { name: 'Sanjay Aggarwal', phone: '9100998877', email: 'sanjay.ag@gmail.com' },
    productService: { products: ['Max EHR Central Module'], services: ['Database Optimization Package'] },
    requestType: { category: 'Product Request', type: 'Enterprise Platform' },
    estDate: '2026-07-06', // Overdue by 1 day
    linkedin: { profile: 'linkedin.com/company/max-healthcare', company: 'linkedin.com/company/max-healthcare' },
    commercial: { opportunities: 1, closingValue: '$165,000', estDealValue: '$82,500', valWithTax: '$194,700', valWithoutTax: '$165,000', commPercent: '10%', commAmount: '$16,500' },
    partners: [],
    history: [{ date: '2026-06-22', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Created' }],
    isOverdue: true
  },
  {
    id: 73, createdAt: '2026-06-23T11:00:00Z', company: 'ICICI Bank Ltd', contact: 'Sandeep Bakhshi',
    stage: 'Negotiation', status: 'Negotiation', value: '$310,000', industry: 'Banking', size: '500+',
    region: 'India', priority: 'Urgent', owner: 'H. Kumar', source: 'Partner', score: 98, prob: 80,
    sentiment: 'Interested', criteria: { bestTime: 'Anytime', requirements: 'High-speed payment log firewall connection' },
    altContact: { name: 'Anup Bagchi', phone: '9900998877', email: 'anup.b@gmail.com' },
    productService: { products: ['ICICI Secure Log Platform'], services: ['Onboard Deployment SLA'] },
    requestType: { category: 'Product Request', type: 'FinTech Platform' },
    estDate: '2026-07-07', // Due Today
    linkedin: { profile: 'linkedin.com/company/icici-bank', company: 'linkedin.com/company/icici-bank' },
    commercial: { opportunities: 2, closingValue: '$310,000', estDealValue: '$248,000', valWithTax: '$365,800', valWithoutTax: '$310,000', commPercent: '10%', commAmount: '$31,000' },
    partners: [],
    history: [{ date: '2026-06-23', action: 'Lead Created', user: 'System', time: '11:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 74, createdAt: '2026-06-24T12:00:00Z', company: 'Axis Bank Ltd', contact: 'Amitabh Chaudhry',
    stage: 'Needs Analysis', status: 'Contacted', value: '$190,000', industry: 'Banking', size: '500+',
    region: 'India', priority: 'High', owner: 'P. Sharma', source: 'Website', score: 83, prob: 40,
    sentiment: 'Neutral', criteria: { bestTime: 'Morning', requirements: 'Encrypted audit databases custom syncing modules' },
    altContact: { name: 'Rajiv Anand', phone: '9888899990', email: 'rajiv.a@gmail.com' },
    productService: { products: ['Axis Crypt Database Connector'], services: ['API Deployment Package'] },
    requestType: { category: 'Product Request', type: 'Enterprise Platform' },
    estDate: '2026-08-30',
    linkedin: { profile: 'linkedin.com/company/axis-bank', company: 'linkedin.com/company/axis-bank' },
    commercial: { opportunities: 1, closingValue: '$190,000', estDealValue: '$76,000', valWithTax: '$224,200', valWithoutTax: '$190,000', commPercent: '10%', commAmount: '$19,000' },
    partners: [],
    history: [{ date: '2026-06-24', action: 'Lead Created', user: 'System', time: '12:00 PM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 75, createdAt: '2026-06-25T13:00:00Z', company: 'Kotak Bank Ltd', contact: 'Uday Kotak',
    stage: 'Proposal', status: 'Proposal Sent', value: '$160,000', industry: 'Banking', size: '500+',
    region: 'India', priority: 'Medium', owner: 'R. Nair', source: 'LinkedIn', score: 81, prob: 50,
    sentiment: 'Positive', criteria: { bestTime: 'Afternoon', requirements: 'Wealth manager dashboard sync modules' },
    altContact: { name: 'Dipak Gupta', phone: '9777755566', email: 'dipak.g@gmail.com' },
    productService: { products: ['Kotak Wealth Manager App Suite'], services: ['Setup Support Package'] },
    requestType: { category: 'Product Request', type: 'Software license' },
    estDate: '2026-07-06', // Overdue by 1 day
    linkedin: { profile: 'linkedin.com/company/kotak-mahindra-bank', company: 'linkedin.com/company/kotak-mahindra-bank' },
    commercial: { opportunities: 1, closingValue: '$160,000', estDealValue: '$80,000', valWithTax: '$188,800', valWithoutTax: '$160,000', commPercent: '10%', commAmount: '$16,000' },
    partners: [],
    history: [{ date: '2026-06-25', action: 'Lead Created', user: 'System', time: '01:00 PM', type: 'system', description: 'Created' }],
    isOverdue: true
  },
  
  // ─── FURTHER EXTENSION (LEADS 76-85 TO SECURE DYNAMIC DIVERSITY) ───
  {
    id: 76, createdAt: '2026-06-26T09:00:00Z', company: 'BigBasket Online', contact: 'Hari Menon',
    stage: 'Prospecting', status: 'New', value: '$80,000', industry: 'E-commerce', size: '100-500',
    region: 'India', priority: 'Normal', owner: 'D. Ghosh', source: 'Google Ads', score: 64, prob: 10,
    sentiment: 'Neutral', criteria: { bestTime: 'Morning', requirements: 'Groceries inventory auto reordering dashboards' },
    altContact: { name: 'Vipul Parekh', phone: '9666677788', email: 'vipul@gmail.com' },
    productService: { products: ['BB Reorder System'], services: ['None'] },
    requestType: { category: 'Product Request', type: 'Software License' },
    estDate: '2026-09-12',
    linkedin: { profile: 'linkedin.com/company/bigbasket', company: 'linkedin.com/company/bigbasket' },
    commercial: { opportunities: 1, closingValue: '$80,000', estDealValue: '$8,000', valWithTax: '$94,400', valWithoutTax: '$80,000', commPercent: '10%', commAmount: '$8,000' },
    partners: [],
    history: [{ date: '2026-06-26', action: 'Lead Created', user: 'System', time: '09:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 77, createdAt: '2026-06-27T10:00:00Z', company: 'Grofers Blinkit', contact: 'Albinder Dhindsa',
    stage: 'Qualification', status: 'Contacted', value: '$70,000', industry: 'E-commerce', size: '100-500',
    region: 'India', priority: 'High', owner: 'S. Mishra', source: 'Facebook Ads', score: 74, prob: 20,
    sentiment: 'Positive', criteria: { bestTime: 'Afternoon', requirements: '10-minute dispatch routing dashboard integration' },
    altContact: { name: 'Saurabh Kumar', phone: '9555566677', email: 'saurabh.k@gmail.com' },
    productService: { products: ['10Min Dispatch Engine'], services: ['API Deployment Package'] },
    requestType: { category: 'Product Request', type: 'Enterprise API' },
    estDate: '2026-08-25',
    linkedin: { profile: 'linkedin.com/company/blinkit', company: 'linkedin.com/company/blinkit' },
    commercial: { opportunities: 1, closingValue: '$70,000', estDealValue: '$14,000', valWithTax: '$82,600', valWithoutTax: '$70,000', commPercent: '10%', commAmount: '$7,000' },
    partners: [],
    history: [{ date: '2026-06-27', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 78, createdAt: '2026-06-28T11:00:00Z', company: 'Hinduja Logistics Ltd', contact: 'Gopichand Hinduja',
    stage: 'Needs Analysis', status: 'Contacted', value: '$190,000', industry: 'Logistics', size: '500+',
    region: 'India', priority: 'High', owner: 'H. Kumar', source: 'LinkedIn', score: 85, prob: 30,
    sentiment: 'Neutral', criteria: { bestTime: 'Morning', requirements: 'Trans-national route optimization API' },
    altContact: { name: 'Ashok Hinduja', phone: '9444455566', email: 'ashok.h@gmail.com' },
    productService: { products: ['TransNational Routing Core'], services: ['API Setup Consulting'] },
    requestType: { category: 'Product Request', type: 'Enterprise API' },
    estDate: '2026-08-10',
    linkedin: { profile: 'linkedin.com/company/hinduja-group', company: 'linkedin.com/company/hinduja-group' },
    commercial: { opportunities: 1, closingValue: '$190,000', estDealValue: '$57,000', valWithTax: '$224,200', valWithoutTax: '$190,000', commPercent: '10%', commAmount: '$19,000' },
    partners: [],
    history: [{ date: '2026-06-28', action: 'Lead Created', user: 'System', time: '11:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 79, createdAt: '2026-06-29T12:00:00Z', company: 'Gati Logistics Ltd', contact: 'Mahendra Agarwal',
    stage: 'Proposal', status: 'Proposal Sent', value: '$160,000', industry: 'Logistics', size: '100-500',
    region: 'India', priority: 'Medium', owner: 'P. Sharma', source: 'Referral', score: 78, prob: 50,
    sentiment: 'Positive', criteria: { bestTime: 'Afternoon', requirements: 'Express delivery tracking portal integration' },
    altContact: { name: 'Bala Aghora', phone: '9333344455', email: 'bala@gmail.com' },
    productService: { products: ['Express Tracker Engine'], services: ['Portal setup Support Package'] },
    requestType: { category: 'Product Request', type: 'Software license' },
    estDate: '2026-07-06', // Overdue by 1 day
    linkedin: { profile: 'linkedin.com/company/gati-ltd', company: 'linkedin.com/company/gati-ltd' },
    commercial: { opportunities: 1, closingValue: '$160,000', estDealValue: '$80,000', valWithTax: '$188,800', valWithoutTax: '$160,000', commPercent: '10%', commAmount: '$16,000' },
    partners: [],
    history: [{ date: '2026-06-29', action: 'Lead Created', user: 'System', time: '12:00 PM', type: 'system', description: 'Created' }],
    isOverdue: true
  },
  {
    id: 80, createdAt: '2026-06-30T13:00:00Z', company: 'VRL Logistics Ltd', contact: 'Vijay Sankeshwar',
    stage: 'Negotiation', status: 'Negotiation', value: '$240,000', industry: 'Logistics', size: '500+',
    region: 'India', priority: 'Urgent', owner: 'R. Nair', source: 'Website', score: 93, prob: 80,
    sentiment: 'Interested', criteria: { bestTime: 'Afternoon', requirements: 'Truck logistics inventory dashboard' },
    altContact: { name: 'Anand Sankeshwar', phone: '9222233344', email: 'anand@gmail.com' },
    productService: { products: ['VRL Truck Logistics Dashboard'], services: ['Setup Support Package'] },
    requestType: { category: 'Product Request', type: 'Enterprise Platform' },
    estDate: '2026-07-07', // Due Today
    linkedin: { profile: 'linkedin.com/company/vrl-logistics', company: 'linkedin.com/company/vrl-logistics' },
    commercial: { opportunities: 2, closingValue: '$240,000', estDealValue: '$192,000', valWithTax: '$283,200', valWithoutTax: '$240,000', commPercent: '10%', commAmount: '$24,000' },
    partners: [],
    history: [{ date: '2026-06-30', action: 'Lead Created', user: 'System', time: '01:00 PM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 81, createdAt: '2026-07-01T09:00:00Z', company: 'Fortis Escorts Med', contact: 'Naresh Trehan',
    stage: 'Needs Analysis', status: 'Contacted', value: '$240,000', industry: 'Healthcare', size: '500+',
    region: 'India', priority: 'High', owner: 'D. Ghosh', source: 'LinkedIn', score: 85, prob: 40,
    sentiment: 'Positive', criteria: { bestTime: 'Afternoon', requirements: 'Secure clinical metrics database interface' },
    altContact: { name: 'Rajiv Gandhi', phone: '9111122233', email: 'rajiv.g@gmail.com' },
    productService: { products: ['Escorts Database Suite'], services: ['HIPAA Compliance Package'] },
    requestType: { category: 'Product Request', type: 'Enterprise Platform' },
    estDate: '2026-08-30',
    linkedin: { profile: 'linkedin.com/company/fortis-escorts', company: 'linkedin.com/company/fortis-escorts' },
    commercial: { opportunities: 1, closingValue: '$240,000', estDealValue: '$96,000', valWithTax: '$283,200', valWithoutTax: '$240,000', commPercent: '10%', commAmount: '$24,000' },
    partners: [],
    history: [{ date: '2026-07-01', action: 'Lead Created', user: 'System', time: '09:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 82, createdAt: '2026-07-02T10:00:00Z', company: 'Manipal Hospitals Group', contact: 'Dr. Sudarshan Ballal',
    stage: 'Prospecting', status: 'New', value: '$310,000', industry: 'Healthcare', size: '500+',
    region: 'India', priority: 'Urgent', owner: 'S. Mishra', source: 'Partner', score: 92, prob: 10,
    sentiment: 'Neutral', criteria: { bestTime: 'Morning', requirements: 'LMS interactive class dashboards' },
    altContact: { name: 'Ranjan Pai', phone: '9900882244', email: 'ranjan@gmail.com' },
    productService: { products: ['Manipal EHR Custom Engine'], services: ['Onboard Deployment SLA'] },
    requestType: { category: 'Product Request', type: 'Enterprise Software' },
    estDate: '2026-10-15',
    linkedin: { profile: 'linkedin.com/company/manipal-hospitals', company: 'linkedin.com/company/manipal-hospitals' },
    commercial: { opportunities: 1, closingValue: '$310,000', estDealValue: '$31,000', valWithTax: '$365,800', valWithoutTax: '$310,000', commPercent: '10%', commAmount: '$31,000' },
    partners: [],
    history: [{ date: '2026-07-02', action: 'Lead Created', user: 'System', time: '10:00 AM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 83, createdAt: '2026-07-03T11:00:00Z', company: 'Sterling Biotech Ltd', contact: 'Chetan Sandesara',
    stage: 'Closed Lost', status: 'Lost', value: '$240,000', industry: 'Healthcare', size: '500+',
    region: 'India', priority: 'High', owner: 'H. Kumar', source: 'Website', score: 81, prob: 0,
    sentiment: 'Negative',
    lostReason: 'Budget Constraints',
    criteria: { bestTime: 'Afternoon', requirements: 'Secure clinical metrics database interface' },
    altContact: { name: 'Nitin Sandesara', phone: '9988114422', email: 'nitin@gmail.com' },
    productService: { products: ['Sterling Database Suite'], services: ['None'] },
    requestType: { category: 'Product Request', type: 'Enterprise Platform' },
    estDate: '2026-07-03',
    linkedin: { profile: 'linkedin.com/company/sterling-biotech', company: 'linkedin.com/company/sterling-biotech' },
    commercial: { opportunities: 1, closingValue: '$240,000', estDealValue: '$0', valWithTax: '$0', valWithoutTax: '$0', commPercent: '0%', commAmount: '$0' },
    partners: [],
    history: [{ date: '2026-07-03', action: 'Lead Created', user: 'System', time: '11:00 AM', type: 'system', description: 'Created' }, { date: '2026-07-03', action: 'Deal Lost', user: 'H. Kumar', time: '05:00 PM', type: 'system', description: 'Lost due to budget constraints' }],
    isOverdue: false
  },
  {
    id: 84, createdAt: '2026-07-04T12:00:00Z', company: 'Dabur India Ltd', contact: 'Amit Burman',
    stage: 'Prospecting', status: 'New', value: '$70,000', industry: 'Manufacturing', size: '500+',
    region: 'India', priority: 'Medium', owner: 'P. Sharma', source: 'Referral', score: 71, prob: 10,
    sentiment: 'Neutral', criteria: { bestTime: 'Morning', requirements: 'LMS interactive class dashboards' },
    altContact: { name: 'Saket Burman', phone: '9977661122', email: 'saket@gmail.com' },
    productService: { products: ['Dabur Logistics Sync App'], services: ['None'] },
    requestType: { category: 'Product Request', type: 'Software License' },
    estDate: '2026-10-01',
    linkedin: { profile: 'linkedin.com/company/dabur', company: 'linkedin.com/company/dabur' },
    commercial: { opportunities: 1, closingValue: '$70,000', estDealValue: '$7,000', valWithTax: '$82,600', valWithoutTax: '$70,000', commPercent: '10%', commAmount: '$7,000' },
    partners: [],
    history: [{ date: '2026-07-04', action: 'Lead Created', user: 'System', time: '12:00 PM', type: 'system', description: 'Created' }],
    isOverdue: false
  },
  {
    id: 85, createdAt: '2026-07-05T13:00:00Z', company: 'Marico India Ltd', contact: 'Harsh Mariwala',
    stage: 'Prospecting', status: 'New', value: '$95,000', industry: 'Manufacturing', size: '500+',
    region: 'India', priority: 'Normal', owner: 'R. Nair', source: 'Google Ads', score: 62, prob: 10,
    sentiment: 'Neutral', criteria: { bestTime: 'Anytime', requirements: 'Multi-store billing integration engine' },
    altContact: { name: 'Rishabh M', phone: '9900883355', email: 'rishabh@gmail.com' },
    productService: { products: ['Marico Billing Suite'], services: ['None'] },
    requestType: { category: 'Product Request', type: 'Software License' },
    estDate: '2026-10-10',
    linkedin: { profile: 'linkedin.com/company/marico', company: 'linkedin.com/company/marico' },
    commercial: { opportunities: 1, closingValue: '$95,000', estDealValue: '$9,500', valWithTax: '$112,100', valWithoutTax: '$95,000', commPercent: '10%', commAmount: '$9,500' },
    partners: [],
    history: [{ date: '2026-07-05', action: 'Lead Created', user: 'System', time: '01:00 PM', type: 'system', description: 'Created' }],
    isOverdue: false
  }
];